# Generated by Django 3.1.3 on 2021-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.IntegerField(db_column='Id_categorie', primary_key=True, serialize=False)),
                ('nom_cat', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
            ],
            options={
                'db_table': 'Categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('num_fact', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('coordonnees_client', models.CharField(max_length=150)),
                ('coordonnees_entreprise', models.CharField(max_length=150)),
                ('date_vente', models.DateField()),
                ('nom_produit', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('prix_ht', models.FloatField()),
                ('tva', models.FloatField()),
                ('prix_ttc', models.FloatField()),
            ],
            options={
                'db_table': 'Facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_pers', models.CharField(db_column='Id_pers', max_length=25, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=75)),
                ('prenom', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Personnel',
                'managed': False,
            },
        ),
    ]
