# Generated by Django 3.1.3 on 2021-02-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factures', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
