# Generated by Django 3.1.3 on 2021-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('num_fact', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('coordonnees_client', models.CharField(max_length=150)),
                ('coordonnees_entreprise', models.CharField(max_length=150)),
                ('date_facture', models.DateField()),
                ('nom_produit', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('prix_ht', models.FloatField()),
                ('tva', models.FloatField()),
                ('prix_ttc', models.FloatField()),
            ],
        ),
    ]
